<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Tutorkrutik' =>'กวดวิชาบ้านครูติ๊กติวเตอร์',
    'Account Settings' => 'ตั้งค่าบัญชี',
    'Profile settings' => 'ตั้งค่าโปรไฟล์',
    'Settings' => 'ตั้งค่า',
    'Service'=>'การบริการ',
    'User Settings' => 'ตั้งค่าผู้ใช้',
    'About' => 'เกี่ยวกับเรา',
    'Articles' => 'บทความ',
    'Attachments' => 'ความผูกพัน',
    'Backend' => 'จัดการระบบ',
    'Body' => 'Cuerpo',
    'Check your email for further instructions.' => 'Verifica tu correo para más instrucciones.',
    'Confirm Password' => 'ยืนยันรหัสผ่าน ',
    'Contact' => 'ติดต่อเรา',
    'E-mail' => 'อีเมล์',
    'Email' => 'อีเมล',
    'Error while oauth process.' => 'Error en el proceso de OAuth.',
    'Female' => 'Mujer',
    'Home' => 'หน้าแรก',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'ลืมรหัสผ่านใช่หรือไม่ <a href="{link}">คลิกที่นี้</a>',
    'Incorrect username or password.' => 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
    'Language' => 'เลือกภาษา',
    'Log in with' => 'Conectado como',
    'Login' => 'เข้าสู่ระบบ',
    'Logout' => 'ออกจากระบบ',
    'Male' => 'Hombre',
    'Name' => 'ชื่อ',
    'Need an account? Sign up.' => 'คุณยังไม่เป็นสมาชิกใช่หรือไหม ลงทะเบียนเดี๋ยวนี้',
    'New password was saved.' => 'La nueva contraseña ha sido guardada',
    'Page not found' => 'Página no encontrada',
    'Password' => 'รหัสผ่าน',
    'Password reset for {name}' => 'Contraseña cambiada para {name}',
    'Remember Me' => 'Recuérdame',
    'Request password reset' => 'Solicita cambio de la contraseña',
    'Reset password' => 'Cambiar Contraseña',
    'Sign up with' => 'Regístrate con',
    'Signup' => 'สมัครสมาชิก',
    'Sorry, we are unable to reset password for email provided.' => 'ขออภัยเราไม่สามารถที่จะตั้งค่ารหัสผ่านสำหรับอีเมลให้ได้.',
    'Subject' => 'Tema',
    'Submit' => 'ตกลง',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Gracias por contactarnos. responderemos tan pronto como sea posible.',
    'There was an error sending email.' => 'Ha ocurrido un error al enviar el correo',
    'This email address has already been taken.' => 'La dirección de correo ya ha sido usada',
    'This username has already been taken.' => 'El nombre de usuario ya está siendo usado',
    'Update' => 'อัพเดต',
    'Username' => 'ชื่อผู้ใช้',
    'Username or email' => 'ชื่อผู้ใช้หรืออีเมล',
    'Verification Code' => 'Código de verificación',
    'We already have a user with email {email}' => 'Ya tenemos un usuario con el correo {email} ',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => '¡Bienvenido a {app-name}!. Un correo con la información de su conexión ha sido enviado a su correo',
    'Your account has been successfully saved' => 'Su cuenta ha sido guardada con éxito',
    '{app-name} | Your login information' => '{app-name} | Información de conexión',
];
